# core_sim/energy.py

def energy(FA_life, enrichment, E_max=100, epsilon=0.05, time=0):
    """
    Calculate the energy generated by a Fuel Assembly (FA) at a given timestep.

    Parameters:
    - FA_life (float): The remaining life of the Fuel Assembly (from 0 to 1) at time t.
    - enrichment (float): Enrichment factor of the FA (between 0 and 1).
    - E_max (float): Maximum energy that the FA can generate (default 100 units).
    - epsilon (float): Energy increase per unit of enrichment (default 0.05).
    - time (float): The current time step in the simulation.

    Returns:
    - float: The calculated energy output of the FA.
    """
    # Energy calculation with time-dependent life
    return E_max * FA_life * (1 + epsilon * enrichment)

def energy_model(FA_life, enrichment, E_max=100, epsilon=0.05, time=0):
    """
    A modular version of the energy calculation, now considering time-dependent life.

    Parameters:
    - FA_life (float): The remaining life of the Fuel Assembly (from 0 to 1) at time t.
    - enrichment (float): Enrichment factor of the FA (between 0 and 1).
    - E_max (float): Maximum energy that the FA can generate (default 100 units).
    - epsilon (float): Energy increase per unit of enrichment (default 0.05).
    - time (float): The current time step in the simulation.

    Returns:
    - float: The calculated energy output of the FA.
    """
    return E_max * FA_life * (1 + epsilon * enrichment)

# Example of a configurable energy model strategy with time consideration
def energy_model_v2(FA_life, enrichment, E_max=100, epsilon=0.1, base_energy=50, time=0):
    """
    A different energy calculation strategy with adjustable parameters, now including time.

    Parameters:
    - FA_life (float): The remaining life of the Fuel Assembly (from 0 to 1) at time t.
    - enrichment (float): Enrichment factor of the FA (between 0 and 1).
    - E_max (float): Maximum energy that the FA can generate (default 100 units).
    - epsilon (float): Energy increase per unit of enrichment (default 0.1).
    - base_energy (float): A baseline energy value to adjust the maximum energy.
    - time (float): The current time step in the simulation.

    Returns:
    - float: The calculated energy output of the FA with this alternate strategy.
    """
    # The time-dependent version of the energy calculation, including time as a factor
    return base_energy * FA_life * (1 + epsilon * enrichment)
