def energy(FA_life, enrichment, E_max=100, epsilon=0.05):
    """
    Calculate the energy generated by a Fuel Assembly (FA).

    Parameters:
    - FA_life (float): The remaining life of the Fuel Assembly (from 0 to 1).
    - enrichment (float): Enrichment factor of the FA (between 0 and 1).
    - E_max (float): Maximum energy that the FA can generate (default 100 units).
    - epsilon (float): Energy increase per unit of enrichment (default 0.05).

    Returns:
    - float: The calculated energy output of the FA.
    """
    return E_max * FA_life * (1 + epsilon * enrichment)
